server:
  port: 8000

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: true
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: false
  thymeleaf:
    cache: false #关闭 Thymeleaf 的缓存，不然在开发过程中修改页面不会立刻生效需要重启，生产可配置为 true
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML5